//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/antoniocortes/j2objcprj/relases/j2objc/testing/mockito/build_result/java/org/mockito/internal/configuration/plugins/PluginLoader.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMockitoInternalConfigurationPluginsPluginLoader")
#ifdef RESTRICT_OrgMockitoInternalConfigurationPluginsPluginLoader
#define INCLUDE_ALL_OrgMockitoInternalConfigurationPluginsPluginLoader 0
#else
#define INCLUDE_ALL_OrgMockitoInternalConfigurationPluginsPluginLoader 1
#endif
#undef RESTRICT_OrgMockitoInternalConfigurationPluginsPluginLoader

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgMockitoInternalConfigurationPluginsPluginLoader_) && (INCLUDE_ALL_OrgMockitoInternalConfigurationPluginsPluginLoader || defined(INCLUDE_OrgMockitoInternalConfigurationPluginsPluginLoader))
#define OrgMockitoInternalConfigurationPluginsPluginLoader_

@class IOSClass;
@protocol OrgMockitoPluginsPluginSwitch;

@interface OrgMockitoInternalConfigurationPluginsPluginLoader : NSObject

#pragma mark Public

- (instancetype __nonnull)initWithOrgMockitoPluginsPluginSwitch:(id<OrgMockitoPluginsPluginSwitch>)pluginSwitch;

#pragma mark Package-Private

/*!
 @brief Equivalent to <code>java.util.ServiceLoader.load</code> but without requiring
  Java 6 / Android 2.3 (Gingerbread).
 */
- (id)loadImplWithIOSClass:(IOSClass *)service;

/*!
 @brief Scans the classpath for given pluginType.If not found, default class is used.
 */
- (id)loadPluginWithIOSClass:(IOSClass *)pluginType
                withNSString:(NSString *)defaultPluginClassName;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMockitoInternalConfigurationPluginsPluginLoader)

FOUNDATION_EXPORT void OrgMockitoInternalConfigurationPluginsPluginLoader_initWithOrgMockitoPluginsPluginSwitch_(OrgMockitoInternalConfigurationPluginsPluginLoader *self, id<OrgMockitoPluginsPluginSwitch> pluginSwitch);

FOUNDATION_EXPORT OrgMockitoInternalConfigurationPluginsPluginLoader *new_OrgMockitoInternalConfigurationPluginsPluginLoader_initWithOrgMockitoPluginsPluginSwitch_(id<OrgMockitoPluginsPluginSwitch> pluginSwitch) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMockitoInternalConfigurationPluginsPluginLoader *create_OrgMockitoInternalConfigurationPluginsPluginLoader_initWithOrgMockitoPluginsPluginSwitch_(id<OrgMockitoPluginsPluginSwitch> pluginSwitch);

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoInternalConfigurationPluginsPluginLoader)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_OrgMockitoInternalConfigurationPluginsPluginLoader")
