//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/antoniocortes/j2objcprj/relases/j2objc/testing/mockito/build_result/java/org/mockito/internal/junit/JUnitRule.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMockitoInternalJunitJUnitRule")
#ifdef RESTRICT_OrgMockitoInternalJunitJUnitRule
#define INCLUDE_ALL_OrgMockitoInternalJunitJUnitRule 0
#else
#define INCLUDE_ALL_OrgMockitoInternalJunitJUnitRule 1
#endif
#undef RESTRICT_OrgMockitoInternalJunitJUnitRule

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgMockitoInternalJunitJUnitRule_) && (INCLUDE_ALL_OrgMockitoInternalJunitJUnitRule || defined(INCLUDE_OrgMockitoInternalJunitJUnitRule))
#define OrgMockitoInternalJunitJUnitRule_

@class OrgJunitRunnersModelStatement;

/*!
 @brief Internal implementation.
 */
@interface OrgMockitoInternalJunitJUnitRule : NSObject

#pragma mark Public

- (instancetype __nonnull)init;

- (OrgJunitRunnersModelStatement *)applyWithOrgJunitRunnersModelStatement:(OrgJunitRunnersModelStatement *)base
                                                                   withId:(id)target;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMockitoInternalJunitJUnitRule)

FOUNDATION_EXPORT void OrgMockitoInternalJunitJUnitRule_init(OrgMockitoInternalJunitJUnitRule *self);

FOUNDATION_EXPORT OrgMockitoInternalJunitJUnitRule *new_OrgMockitoInternalJunitJUnitRule_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMockitoInternalJunitJUnitRule *create_OrgMockitoInternalJunitJUnitRule_init(void);

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoInternalJunitJUnitRule)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_OrgMockitoInternalJunitJUnitRule")
