//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/antoniocortes/j2objcprj/relases/j2objc/testing/mockito/build_result/java/org/mockito/verification/VerificationWrapper.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMockitoVerificationVerificationWrapper")
#ifdef RESTRICT_OrgMockitoVerificationVerificationWrapper
#define INCLUDE_ALL_OrgMockitoVerificationVerificationWrapper 0
#else
#define INCLUDE_ALL_OrgMockitoVerificationVerificationWrapper 1
#endif
#undef RESTRICT_OrgMockitoVerificationVerificationWrapper

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgMockitoVerificationVerificationWrapper_) && (INCLUDE_ALL_OrgMockitoVerificationVerificationWrapper || defined(INCLUDE_OrgMockitoVerificationVerificationWrapper))
#define OrgMockitoVerificationVerificationWrapper_

#define RESTRICT_OrgMockitoVerificationVerificationMode 1
#define INCLUDE_OrgMockitoVerificationVerificationMode 1
#include "org/mockito/verification/VerificationMode.h"

@protocol OrgMockitoInternalVerificationApiVerificationData;

@interface OrgMockitoVerificationVerificationWrapper : NSObject < OrgMockitoVerificationVerificationMode > {
 @public
  id<OrgMockitoVerificationVerificationMode> wrappedVerification_;
}

#pragma mark Public

- (instancetype __nonnull)initWithOrgMockitoVerificationVerificationMode:(id<OrgMockitoVerificationVerificationMode>)wrappedVerification;

- (id<OrgMockitoVerificationVerificationMode>)atLeastWithInt:(jint)minNumberOfInvocations;

- (id<OrgMockitoVerificationVerificationMode>)atLeastOnce;

- (id<OrgMockitoVerificationVerificationMode>)atMostWithInt:(jint)maxNumberOfInvocations;

- (id<OrgMockitoVerificationVerificationMode>)never;

- (id<OrgMockitoVerificationVerificationMode>)only;

- (id<OrgMockitoVerificationVerificationMode>)timesWithInt:(jint)wantedNumberOfInvocations;

- (void)verifyWithOrgMockitoInternalVerificationApiVerificationData:(id<OrgMockitoInternalVerificationApiVerificationData>)data;

#pragma mark Protected

- (id<OrgMockitoVerificationVerificationMode>)copySelfWithNewVerificationModeWithOrgMockitoVerificationVerificationMode:(id<OrgMockitoVerificationVerificationMode>)verificationMode OBJC_METHOD_FAMILY_NONE;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMockitoVerificationVerificationWrapper)

J2OBJC_FIELD_SETTER(OrgMockitoVerificationVerificationWrapper, wrappedVerification_, id<OrgMockitoVerificationVerificationMode>)

FOUNDATION_EXPORT void OrgMockitoVerificationVerificationWrapper_initWithOrgMockitoVerificationVerificationMode_(OrgMockitoVerificationVerificationWrapper *self, id<OrgMockitoVerificationVerificationMode> wrappedVerification);

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoVerificationVerificationWrapper)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_OrgMockitoVerificationVerificationWrapper")
