//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/antoniocortes/j2objcprj/relases/j2objc/testing/mockito/build_result/java/org/mockito/internal/invocation/finder/VerifiableInvocationsFinder.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMockitoInternalInvocationFinderVerifiableInvocationsFinder")
#ifdef RESTRICT_OrgMockitoInternalInvocationFinderVerifiableInvocationsFinder
#define INCLUDE_ALL_OrgMockitoInternalInvocationFinderVerifiableInvocationsFinder 0
#else
#define INCLUDE_ALL_OrgMockitoInternalInvocationFinderVerifiableInvocationsFinder 1
#endif
#undef RESTRICT_OrgMockitoInternalInvocationFinderVerifiableInvocationsFinder

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgMockitoInternalInvocationFinderVerifiableInvocationsFinder_) && (INCLUDE_ALL_OrgMockitoInternalInvocationFinderVerifiableInvocationsFinder || defined(INCLUDE_OrgMockitoInternalInvocationFinderVerifiableInvocationsFinder))
#define OrgMockitoInternalInvocationFinderVerifiableInvocationsFinder_

@protocol JavaUtilList;

/*!
 @brief Author: Szczepan Faber, created at: 4/3/11
 */
@interface OrgMockitoInternalInvocationFinderVerifiableInvocationsFinder : NSObject

#pragma mark Public

- (instancetype __nonnull)init;

- (id<JavaUtilList>)findWithJavaUtilList:(id<JavaUtilList>)mocks;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMockitoInternalInvocationFinderVerifiableInvocationsFinder)

FOUNDATION_EXPORT void OrgMockitoInternalInvocationFinderVerifiableInvocationsFinder_init(OrgMockitoInternalInvocationFinderVerifiableInvocationsFinder *self);

FOUNDATION_EXPORT OrgMockitoInternalInvocationFinderVerifiableInvocationsFinder *new_OrgMockitoInternalInvocationFinderVerifiableInvocationsFinder_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMockitoInternalInvocationFinderVerifiableInvocationsFinder *create_OrgMockitoInternalInvocationFinderVerifiableInvocationsFinder_init(void);

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoInternalInvocationFinderVerifiableInvocationsFinder)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_OrgMockitoInternalInvocationFinderVerifiableInvocationsFinder")
