//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/antoniocortes/j2objcprj/relases/j2objc/testing/mockito/build_result/java/org/mockito/internal/junit/JUnitDetecter.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMockitoInternalJunitJUnitDetecter")
#ifdef RESTRICT_OrgMockitoInternalJunitJUnitDetecter
#define INCLUDE_ALL_OrgMockitoInternalJunitJUnitDetecter 0
#else
#define INCLUDE_ALL_OrgMockitoInternalJunitJUnitDetecter 1
#endif
#undef RESTRICT_OrgMockitoInternalJunitJUnitDetecter

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgMockitoInternalJunitJUnitDetecter_) && (INCLUDE_ALL_OrgMockitoInternalJunitJUnitDetecter || defined(INCLUDE_OrgMockitoInternalJunitJUnitDetecter))
#define OrgMockitoInternalJunitJUnitDetecter_

@interface OrgMockitoInternalJunitJUnitDetecter : NSObject

#pragma mark Public

- (jboolean)hasJUnit;

#pragma mark Package-Private

- (instancetype __nonnull)init;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMockitoInternalJunitJUnitDetecter)

FOUNDATION_EXPORT void OrgMockitoInternalJunitJUnitDetecter_init(OrgMockitoInternalJunitJUnitDetecter *self);

FOUNDATION_EXPORT OrgMockitoInternalJunitJUnitDetecter *new_OrgMockitoInternalJunitJUnitDetecter_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMockitoInternalJunitJUnitDetecter *create_OrgMockitoInternalJunitJUnitDetecter_init(void);

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoInternalJunitJUnitDetecter)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_OrgMockitoInternalJunitJUnitDetecter")
