//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/antoniocortes/j2objcprj/relases/j2objc/testing/mockito/build_result/java/org/mockito/plugins/PluginSwitch.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMockitoPluginsPluginSwitch")
#ifdef RESTRICT_OrgMockitoPluginsPluginSwitch
#define INCLUDE_ALL_OrgMockitoPluginsPluginSwitch 0
#else
#define INCLUDE_ALL_OrgMockitoPluginsPluginSwitch 1
#endif
#undef RESTRICT_OrgMockitoPluginsPluginSwitch

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgMockitoPluginsPluginSwitch_) && (INCLUDE_ALL_OrgMockitoPluginsPluginSwitch || defined(INCLUDE_OrgMockitoPluginsPluginSwitch))
#define OrgMockitoPluginsPluginSwitch_

/*!
 @brief Allows switching off the plugins that are discovered on classpath.
 When a particular plugin is switched off, the default Mockito behavior is used.
  For example, if Android's dexmaker MockMaker is switched off,
  Mockito default MockMaker implementation is used <code>org.mockito.plugins.MockMaker</code>
 @since 1.10.15
 */
@protocol OrgMockitoPluginsPluginSwitch < JavaObject >

/*!
 @brief Mockito invokes this method for every plugin found in the classpath
  (except from the <code>PluginSwitch</code> implementation itself).
 If no custom plugins are discovered this method is not invoked.
 @since 1.10.15
 */
- (jboolean)isEnabledWithNSString:(NSString *)pluginClassName;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMockitoPluginsPluginSwitch)

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoPluginsPluginSwitch)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_OrgMockitoPluginsPluginSwitch")
