//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/antoniocortes/j2objcprj/relases/j2objc/testing/mockito/build_result/java/org/mockito/internal/exceptions/MockitoLimitations.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMockitoInternalExceptionsMockitoLimitations")
#ifdef RESTRICT_OrgMockitoInternalExceptionsMockitoLimitations
#define INCLUDE_ALL_OrgMockitoInternalExceptionsMockitoLimitations 0
#else
#define INCLUDE_ALL_OrgMockitoInternalExceptionsMockitoLimitations 1
#endif
#undef RESTRICT_OrgMockitoInternalExceptionsMockitoLimitations

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgMockitoInternalExceptionsMockitoLimitations_) && (INCLUDE_ALL_OrgMockitoInternalExceptionsMockitoLimitations || defined(INCLUDE_OrgMockitoInternalExceptionsMockitoLimitations))
#define OrgMockitoInternalExceptionsMockitoLimitations_

@interface OrgMockitoInternalExceptionsMockitoLimitations : NSObject
@property (readonly, copy, class) NSString *NON_PUBLIC_PARENT NS_SWIFT_NAME(NON_PUBLIC_PARENT);

+ (NSString *)NON_PUBLIC_PARENT;

#pragma mark Public

- (instancetype __nonnull)init;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMockitoInternalExceptionsMockitoLimitations)

inline NSString *OrgMockitoInternalExceptionsMockitoLimitations_get_NON_PUBLIC_PARENT(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgMockitoInternalExceptionsMockitoLimitations_NON_PUBLIC_PARENT;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgMockitoInternalExceptionsMockitoLimitations, NON_PUBLIC_PARENT, NSString *)

FOUNDATION_EXPORT void OrgMockitoInternalExceptionsMockitoLimitations_init(OrgMockitoInternalExceptionsMockitoLimitations *self);

FOUNDATION_EXPORT OrgMockitoInternalExceptionsMockitoLimitations *new_OrgMockitoInternalExceptionsMockitoLimitations_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMockitoInternalExceptionsMockitoLimitations *create_OrgMockitoInternalExceptionsMockitoLimitations_init(void);

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoInternalExceptionsMockitoLimitations)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_OrgMockitoInternalExceptionsMockitoLimitations")
