//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/antoniocortes/j2objcprj/relases/j2objc/testing/mockito/build_result/java/org/mockito/junit/MockitoJUnitRule.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMockitoJunitMockitoJUnitRule")
#ifdef RESTRICT_OrgMockitoJunitMockitoJUnitRule
#define INCLUDE_ALL_OrgMockitoJunitMockitoJUnitRule 0
#else
#define INCLUDE_ALL_OrgMockitoJunitMockitoJUnitRule 1
#endif
#undef RESTRICT_OrgMockitoJunitMockitoJUnitRule

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgMockitoJunitMockitoJUnitRule_) && (INCLUDE_ALL_OrgMockitoJunitMockitoJUnitRule || defined(INCLUDE_OrgMockitoJunitMockitoJUnitRule))
#define OrgMockitoJunitMockitoJUnitRule_

#define RESTRICT_OrgJunitRulesMethodRule 1
#define INCLUDE_OrgJunitRulesMethodRule 1
#include "org/junit/rules/MethodRule.h"

#define RESTRICT_OrgMockitoJunitMockitoRule 1
#define INCLUDE_OrgMockitoJunitMockitoRule 1
#include "org/mockito/junit/MockitoRule.h"

@class OrgJunitRunnersModelFrameworkMethod;
@class OrgJunitRunnersModelStatement;

/*!
 @brief Please use <code>MockitoJUnit.rule()</code> instead of direct use.
 The reason of the deprecation is that we want to avoid concrete classes in the public api.
 - seealso: MockitoJUnit
 @since 1.10.6
 */
__attribute__((deprecated))
@interface OrgMockitoJunitMockitoJUnitRule : NSObject < OrgJunitRulesMethodRule, OrgMockitoJunitMockitoRule >

#pragma mark Public

/*!
 @brief Please use <code>MockitoJUnit.rule()</code>.
 The reason of the deprecation is that we want to avoid concrete classes in the public api.
 */
- (instancetype __nonnull)init __attribute__((deprecated));

/*!
 @brief Please use <code>MockitoJUnit.rule()</code>.
 The reason of the deprecation is that we want to avoid concrete classes in the public api.
 */
- (instancetype __nonnull)initWithId:(id)targetTest __attribute__((deprecated));

- (OrgJunitRunnersModelStatement *)applyWithOrgJunitRunnersModelStatement:(OrgJunitRunnersModelStatement *)base
                                  withOrgJunitRunnersModelFrameworkMethod:(OrgJunitRunnersModelFrameworkMethod *)method
                                                                   withId:(id)target;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMockitoJunitMockitoJUnitRule)

FOUNDATION_EXPORT void OrgMockitoJunitMockitoJUnitRule_init(OrgMockitoJunitMockitoJUnitRule *self);

FOUNDATION_EXPORT OrgMockitoJunitMockitoJUnitRule *new_OrgMockitoJunitMockitoJUnitRule_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMockitoJunitMockitoJUnitRule *create_OrgMockitoJunitMockitoJUnitRule_init(void);

FOUNDATION_EXPORT void OrgMockitoJunitMockitoJUnitRule_initWithId_(OrgMockitoJunitMockitoJUnitRule *self, id targetTest);

FOUNDATION_EXPORT OrgMockitoJunitMockitoJUnitRule *new_OrgMockitoJunitMockitoJUnitRule_initWithId_(id targetTest) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMockitoJunitMockitoJUnitRule *create_OrgMockitoJunitMockitoJUnitRule_initWithId_(id targetTest);

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoJunitMockitoJUnitRule)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_OrgMockitoJunitMockitoJUnitRule")
